name: ryu-cho

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # on button click

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          username: mostafa-nematpour
          email: "nematpor46@gmail.com"

          upstream-repo: https://github.com/mostafa-nematpour/vite-docs-fa.git
          upstream-repo-branch: main

          head-repo: https://github.com/vitejs/vite
          head-repo-branch: main
          track-from: 344642ad630d8658308dbf707ed805cb04b49d58
          path-starts-with: docs/
          workflow-name: ryu-cho
