name: Sync Vite Docs

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync Vite docs
        run: |
          DATE=$(date +%Y%m%d)
          BRANCH_NAME="upstream-sync"

          git remote add upstream https://github.com/vitejs/vite.git
          git fetch upstream

          git checkout $BRANCH_NAME

          git checkout upstream/main -- docs

          if [[ -n $(git status -s) ]]; then
            git add docs
            git commit -m "sync: Update Vite docs from upstream $DATE"
            git push origin $BRANCH_NAME
          fi
